"use client"
import React from 'react';
import { AuthContextProvider } from '@/context/AuthContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ChatContextProvider from '@/context/ChatContext';
import { ChakraProvider } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chatwithme',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
    >
      <head>
        <title>Chatwithme</title>
      </head>
      <AuthContextProvider>
        <ChatContextProvider>
          <ChakraProvider>
            <body className={inter.className}>
              <div
                className="bg-white w-full h-[100vh]"
              >
                {children}
              </div>
            </body>
          </ChakraProvider>
        </ChatContextProvider>
      </AuthContextProvider>
    </html>
  )
}
